---
kind: pipeline
name: default

platform:
  arch: amd64

steps: 
- name: Build
  image: plugins/hugo
  settings:
    hugo_version: 0.68
    url: https://alca.dev
    output: public/
    validate: true

- name: Deploy
  image: appleboy/drone-scp
  settings:
    host: 
      from_secret: SCARLET_HOST
    user: 
      from_secret: SCARLET_USER
    password:
      from_secret: SCARLET_KEY
    port: 22
    target:
      from_secret: ALCA_DEPLOY_PATH
    source: public/*
