---
kind: pipeline
name: default

platform:
  arch: amd64

steps: 
- name: Build
  image: plugins/hugo
  settings:
    hugo_version: 0.82.1
    url: https://alca.dev
    output: public/
    validate: true
    extended: true

- name: Deploy
  image: alpine:latest
  commands:
    - apk add --no-cache openssh-client ca-certificates bash
    - apk add rsync
    - eval `ssh-agent -s`
    - echo "$KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -avzr --delete -e "ssh -p 22" --progress public/ ubuntu@alca.dev:/opt/serve/alca.dev
  environment:
    KEY:
      from_secret: SCARLET_KEY
