baseURL = "https://alca.dev"
theme = "risotto" # With custom Tokyo Night colorscheme
title = "Berkcan Uçan"
author = "Berkcan Uçan"
#copyright = "Berkcan Uçan"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

# Enable robots
enableRobotsTXT = true

[sitemap]
  filename = 'sitemap.xml'

[params]
  mainSections = ["tldr", "post", "gpg"]

[params.theme]
palette = "tokyonight"
mode = "dark-mode"

# Sidebar: about/bio
[params.about]
title = ""
description = "Greetings! 🌟 Berkcan here, your friendly neighborhood Full Stack Developer. I have a passion for discovering and tinkering with bleeding-edge tech."
keywords = ["alcadramin","alca.dev","berkcan","berkcan ucan","berkcan uçan","blog","web log","alca","alca logs"]
logo = "logo.png"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/Alcadramin"

[[params.socialLinks]]
icon = "fa-brands fa-spotify"
title = "Spotify"
url = "https://open.spotify.com/user/ectheliona?si=93b77000f35c487d"

[[params.socialLinks]]
icon = "fa-solid fa-yin-yang"
title = "Codewars"
url = "https://codewars.alca.dev"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:hello@alca.dev"

[menu]
  [[menu.main]]
    identifier = "gpg"
    name = "GPG"
    url = "/gpg/"
    weight = 70

  [[menu.main]]
    identifier = "post"
    name = "Posts"
    url = "/post/"
    weight = 60

  [[menu.main]]
    identifier = "tldr"
    name = "TL;DR;"
    url = "/tldr/"
    weight = 50

[taxonomies]
  category = "Categories"
  tag = "Tags"
  series = "Series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
